name: Publish Package
on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '12.x'
            - name: Install
              run: yarn install
            - name: Build
              run: yarn test
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
